### ISSUE TITLE
Add parameters matching

### ISSUE THREAD

**Issue by bemble** [pierrecle/gherkin-specs#1]
> When text contains double quotes handle their content as function parameter.
## Sample 1

``` gherkin
Given My name is "Pierre"
```

Would give that spec:

``` javascript
.given(/^My name is "(.*)"$/, (arg1) => {})
```
## Sample 2

``` gherkin
Given I'm "30"
```

Would give that spec:

``` javascript
.given(/^I'm "(.*)"$/, (arg1) => {
  arg1 = parseInt(arg1);
})
```
## Tasks
- [X] do it by default
- [X] add an option to disable it
- [x] handle `scenario outline` and take names from there
- [ ] ~~add needed casts (add an option for that), don't forget Typescript types~~
