### ISSUE TITLE
Don't overwrite existing specs

### ISSUE THREAD

**Issue by bemble** [pierrecle/gherkin-specs#2]
> Instead of overwriting specs, load the implementation and just add missing steps.
## Tasks
- [ ] read existing specs
- [ ] don't overwrite existing implementation
- [ ] append missing specs
- [ ] add a comment below steps not in feature anymore
